// This file is generated by mmltk_browser_host_contract_codegen. Do not edit by hand.
// Contract hash: ab33a7f1017bb4973aba084519ebe9db48c2c6a115a43a16bce5c7901676a71b

#pragma once

#include <string_view>

namespace mmltk::browser {

inline constexpr std::string_view kBrowserUiContractHash = "ab33a7f1017bb4973aba084519ebe9db48c2c6a115a43a16bce5c7901676a71b";

}  // namespace mmltk::browser
