// This file is generated by mmltk_browser_host_contract_codegen. Do not edit by hand.
// Contract hash: bb6b37362663fc0e99bb4e0e29b82270b8ffa32ab7101e6c481389b8214e1899

#pragma once

#include <string_view>

namespace mmltk::browser {

inline constexpr std::string_view kBrowserUiContractHash = "bb6b37362663fc0e99bb4e0e29b82270b8ffa32ab7101e6c481389b8214e1899";

}  // namespace mmltk::browser
