// This file is generated by mmltk_browser_host_contract_codegen. Do not edit by hand.
// Contract hash: ab33a7f1017bb4973aba084519ebe9db48c2c6a115a43a16bce5c7901676a71b

export const HOST_API_PROTOCOL_VERSION = 2 as const;
export const HOST_API_CONTRACT_HASH = "ab33a7f1017bb4973aba084519ebe9db48c2c6a115a43a16bce5c7901676a71b" as const;
export const HOST_API_WORKFLOWS = [
  "train",
  "validate",
  "predict",
  "annotate",
  "export",
  "live"
] as const;
export const HOST_API_FILE_DIALOG_MODES = [
  "open_file",
  "open_folder",
  "save_file"
] as const;
export const HOST_API_INTENTS = [
  "train.start",
  "train.stop",
  "train.remote.query",
  "train.local_gpu.refresh",
  "train.remote.offer.arm",
  "train.remote.offer.clear",
  "train.remote.start",
  "train.remote.stop",
  "predict.start",
  "predict.stop",
  "validate.start",
  "export.start",
  "annotate.save",
  "annotate.save_now",
  "annotate.live.start",
  "annotate.live.stop",
  "annotate.setup_frame.reload",
  "annotate.setup_frame.prev",
  "annotate.setup_frame.next",
  "annotate.hold_save",
  "annotate.brush_radius",
  "annotate.sidebar",
  "annotate.workspace.click",
  "annotate.workspace.box_drag",
  "annotate.workspace.handle_drag",
  "annotate.workspace.brush",
  "annotate.workspace.pointer",
  "annotate.workspace.fill",
  "annotate.workspace.color_sample",
  "tool.select",
  "live.preview.fit_to_capture",
  "live.preview.full_frame_display",
  "settings.update",
  "workspace.drawn",
  "workspace.imported",
  "workspace.import_failed",
  "workspace.acquire_failed",
  "workspace.release_complete",
  "workspace.release_rejected",
  "workspace.bounds",
  "crop.commit",
  "file_dialog.request",
  "viewport.commit"
] as const;

export type HostApiGeneratedWorkflow = (typeof HOST_API_WORKFLOWS)[number];
export type HostApiGeneratedIntent = (typeof HOST_API_INTENTS)[number];
export type Workflow = HostApiGeneratedWorkflow;
export type SourceKind = "compiled_dataset" | "single_image" | "image_folder" | "video_stream";
export type BrowserHostBackend = "unknown" | "cef";
export type BrowserRuntimeCapabilityStatus = "unknown" | "available" | "unavailable";
export type FileDialogMode = (typeof HOST_API_FILE_DIALOG_MODES)[number];

export interface CaptureRegion {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface JobLogEntry {
  sequence: number;
  level: string;
  message: string;
}

export interface JobState {
  running: boolean;
  label: string;
  summary: string;
  error: string;
  output_tail: string;
  recent_logs: JobLogEntry[];
}

export interface SourceMetadata {
  kind: SourceKind;
  locator: string;
  recursive: boolean;
  device_index: number;
  capture_width: number;
  capture_height: number;
  capture_fps: number;
  v4l2_buffer_count: number;
  has_crop: boolean;
  crop: CaptureRegion;
}

export interface AnnotationDocumentState {
  document_generation: number;
  session_revision: number;
  capture_width: number;
  capture_height: number;
  instance_count: number;
  selected_instance: number | null;
}

export interface WorkspaceSurfaceInfo {
  surfaceId: "workspace";
  revision: string;
  width: number;
  height: number;
  textureFormat: "rgba8unorm";
  opaque: true;
  upright: true;
}

export interface BrowserRuntimeCapabilities {
  host_backend: BrowserHostBackend;
  navigator_gpu: BrowserRuntimeCapabilityStatus;
  workspace_surface_bridge: BrowserRuntimeCapabilityStatus;
  workspace_surface_zero_copy: BrowserRuntimeCapabilityStatus;
}

export interface StateSnapshot {
  type: "state.snapshot";
  protocol_version: number;
  contract_hash: string;
  state_revision: number;
  active_workflow: Workflow;
  workflow_state: Record<string, unknown>;
  settings_state: Record<string, unknown>;
  job: JobState;
  source: SourceMetadata;
  annotation: AnnotationDocumentState;
  runtime_capabilities: BrowserRuntimeCapabilities;
  workspace_surface?: WorkspaceSurfaceInfo | null;
}

export interface IntentMessage {
  type: "intent";
  protocol_version: number;
  request_id: number;
  workflow: Workflow;
  intent: string;
  payload: Record<string, unknown>;
}
